import os
import json
import pandas as pd
import time
from pathlib import Path
from google import genai
from google.genai import types

class DeepRecallJudge:
    def __init__(self, predictions_csv: str = "v1/artifacts/predictions/rag_vs_deep_recall_results.csv"):
        self.predictions_csv = Path(predictions_csv)
        api_key = os.environ.get("GEMINI_API_KEY")
        self.client = genai.Client(api_key=api_key)
        self.results_path = Path("v1/artifacts/llm_judge/deep_recall_judge_results.json")

    def judge(self):
        df = pd.read_csv(self.predictions_csv)
        judged_results = []

        sys_instr = """
You are an expert narrative analyst and impartial judge. 
Your task is to evaluate internal monologues generated by an AI assistant for a specific persona.
"""

        prompt_template = """
Persona: {persona}
Anchor Event: {anchor}
Retrieved Memories:
{context}

Response to Evaluate:
{response}

---
TASK: Rate the response on a scale of 1 to 5 for the following dimensions:
1. Accuracy: Does the monologue accurately and naturally incorporate the provided context memories?
2. Coherence: Is the monologue logically sound and narratively consistent with the persona?
3. Emotional Tone: Does the monologue capture the appropriate emotional weight and resonance given the anchor and memories?

Respond ONLY with a JSON object: {{"accuracy": int, "coherence": int, "emotional_tone": int, "reasoning": str}}
"""

        for i, row in df.iterrows():
            print(f">>> Judging Story {row['story_id']}...")
            
            # Judge RAG
            print("    Judging RAG response...")
            prompt_rag = prompt_template.format(
                persona=row['persona'],
                anchor=row['anchor'],
                context=row['rag_context'],
                response=row['rag_response']
            )
            score_rag = self.safe_judge_call(sys_instr, prompt_rag)
            
            # Judge ALS
            print("    Judging ALS (Deep Recall) response...")
            prompt_als = prompt_template.format(
                persona=row['persona'],
                anchor=row['anchor'],
                context=row['als_context'],
                response=row['als_response']
            )
            score_als = self.safe_judge_call(sys_instr, prompt_als)

            judged_results.append({
                "story_id": row['story_id'],
                "rag_scores": score_rag,
                "als_scores": score_als
            })
            time.sleep(1)

        # Save results
        with open(self.results_path, "w", encoding="utf-8") as f:
            json.dump(judged_results, f, indent=4)
        
        self.summarize(judged_results)

    def safe_judge_call(self, sys_instr, prompt):
        for _ in range(3):
            try:
                response = self.client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=sys_instr,
                        response_mime_type="application/json"
                    )
                )
                return json.loads(response.text)
            except Exception as e:
                print(f"      Judge error: {e}")
                time.sleep(2)
        return {"accuracy": 0, "coherence": 0, "emotional_tone": 0, "reasoning": "Error"}

    def summarize(self, results):
        metrics = ["accuracy", "coherence", "emotional_tone"]
        rag_avgs = {m: 0 for m in metrics}
        als_avgs = {m: 0 for m in metrics}
        n = len(results)

        for res in results:
            for m in metrics:
                rag_avgs[m] += res["rag_scores"].get(m, 0)
                als_avgs[m] += res["als_scores"].get(m, 0)
        
        print("\n=== FINAL JUDGE SUMMARY (Averages) ===")
        print(f"{'Metric':<20} | {'Standard RAG':<15} | {'Deep Recall (ALS)':<15}")
        print("-" * 55)
        for m in metrics:
            r_avg = rag_avgs[m] / n
            a_avg = als_avgs[m] / n
            print(f"{m.replace('_', ' ').title():<20} | {r_avg:<15.2f} | {a_avg:<15.2f}")
        print("-" * 55)

if __name__ == "__main__":
    judge = DeepRecallJudge()
    judge.judge()
